// Generated by scripts/generate_chromium_bridge_contract. Do not edit.

public enum KeywayChromiumBridgeContract {
    public static let protocolVersion = 4
    public static let nativeMessagingHostName = "com.fpieringer.keyway.chromium"
    public static let extensionID = "gmdpkggbaohimgacbclndlfjghgcbael"
    public static let appBundleIdentifier = "com.fpieringer.Keyway"
    public static let nativeHostCodeIdentifier = "keyway-chromium-native-host"
    public static let teamIdentifier = "7Q44SDV7BM"
}
